### ISSUE TITLE
开智部落月度成长笔记

### ISSUE THREAD

**Issue by violettianjie** [violettianjie/violetpalace#8]
# 201701 解题人生

- 学习主题： 如何学习

[《怎样解题》](https://github.com/OpenMindClub/OpenMindWorld/issues/115)、[《脑的阅读》](https://github.com/OpenMindClub/OpenMindWorld/issues/122)、[《为什么学生不喜欢上学》](https://github.com/OpenMindClub/OpenMindWorld/issues/133)
一月读了三本书，每本书读一章，其实只读了三章，但是尝试了一种新的解题思路。某种意义上说，我们的人生，就是不断遇到问题，不断解决问题的人生。

用《怎样解题》书里的方法去解决问题。发现了新的更多问题。然后再解决，再复盘。突然，对人生遇到的各种问题，有了新的体会。

1月21日，从深圳回到成都。1月22日，组织了一场在成都的聚会。本着学习要输出的观点，把我学到的一些观点分享给自己在成都的小伙伴们，也听她们分享了2016年的收获，2017年的展望。

这种组织活动，形式的输出，是用批量解决问题的实践，解决了春节没有足够多的时间见所有的小伙伴们的问题； 也是用学习就要输出的实践，给小伙伴们汇报了我到深圳后的一些收获，也增强了彼此的了解；也是成本最省的实践，大家在一起 每人做一道菜，一起吃饭一起下午茶，一起分享，再一起学习做胸花簪花，实现了倍增的效应。大家都很开心。

# 解题之乐  不亦乐乎

![image](https://cloud.githubusercontent.com/assets/24457992/23157930/04d889a6-f858-11e6-937d-886584d4ad6a.png)

群聊里，有朋友出了这样一道题。第一反应，怎么输入这个公式。答案是这个公式，只是怎么输入是一个问题。

后来，去查了答案，为0。但是不明白为什么。于是又去查，了解到**奇函数在对称积分区间上的定积分结果为0。**

于是了解了答案的思路。

再用《怎样解题》里的思路反思： 第一个自己犯的错误，并没有了解题目，也没有了解未知量是什么。 题目要的答案应该是数字，而不是公式。而我没有去找微积分相关内容，定义这个题目。如果能查到这个属于定积分，奇函数（几个大学里学过的概念），就可以解答这个问题。

按照《怎样解题》的思路：

> 

> 解题的一般过程:
> •	第一,你必须理解题目
> 未知量是什么?已知数据是什么?条件是什么?
> 条件有可能满足吗?条件是否足以确定未知量?或者它不够充分?或者多余?或者矛盾?
> 画一张图,引入适当的符号。
> 将条件的不同部分分开。你能把它们写出来吗?

> •	第二,拟订解题方案
> 找出已知数据与未知量之间的联系。
> 如果找不到直接的联系,你也许不得不去考虑辅助题目。
> 最终你应该得到一个解题方案。
> 如果你不能解题,先尝试去解相关题目。

> •	第三,执行解题方案
> 执行你的解题方案,检查每一个步骤。
> 你能清楚地看出这个步骤是正确的吗?
> 你能否证明它是正确的?

> •	第四,检查回顾
> 检查已经得到的解答。
> 你能检验这个结果吗?
> 你能检验这个论证吗?
> 你能一眼就看出它来吗?
> 你能在别的什么题目中利用这个结果或这种方法吗?
> 

回溯了微积分的源头：牛顿和莱布尼茨 Gottfried Wilhelm Leibniz。

- 莱布尼茨（Gottfried Wilhelm Leibniz）（1646.7.1－1716.11.14）
德国哲学家，数学家。
14岁上大学，20岁分别拿到莱比锡大学，University of Altdorf两个大学的博士学位。（大牛）
19岁写了第一本书《论组合术》
去世前，写有《论中国人的自然神学》。

再从莱布尼茨，过渡到了解笛卡尔，然后把《怎样解题》里《探索法》相关的几个人名串起来了，发现了作者的一些内在写作逻辑。如同捡到一串珍珠项链，欣喜如同收到一份礼物。

书里小词典里标题里提到三个人物，看看他们的出生年代，非常有意思的串联起来，笛卡尔Rene Descartes（1596.3.31—1650.2.11）去世后，有了莱布尼茨，莱布尼茨去世后有了波尔查诺Bernard Bolzano（1781.10.15-1848.12.18），波尔查诺之后 有了波利亚。他们的文字著作中，都有对探索法的一些思考和理解，波利亚George Pólya （1887.12,13-1985.9,7）的书里非常有意思的把它们串联起来了，每一个珠子都熠熠生辉。当然，更早的来源可能是 希腊的 帕普斯。从时间的脉络，去理解他们的思想，关于探索法，有豁然开朗之感。

数学家的书，看似零乱，其实内在充满逻辑，需要我们自己去睁大双眼发现这数学之美。

如同笛卡尔《方法论》中说：

> 
> 1. 永远不接受任何我自己不清楚的真理，就是说要尽量避免鲁莽和偏见，只能是根据自己的判断非常清楚和确定，没有任何值得怀疑的地方的真理。就是说只要没有经过自己切身体会的问题，不管有什么权威的结论，都可以怀疑。这就是著名的“怀疑一切”理论。
> 2. 可以将要研究的复杂问题，尽量分解为多个比较简单的小问题，一个一个地分开解决。
> 3. 将这些小问题从简单到复杂排列，先从容易解决的问题着手。
> 4. 将所有问题解决后，再综合起来检验，看是否完全，是否将问题彻底解决了。
 

 这个过程充满了乐趣。解题之乐，数学之美。如同
> 天上有行云，人在行云里。

数学、文学之美交相辉映，照耀我们的世界。

**Comment by violettianjie** [comment]
# 201702 做自己的主人


- 《心灵种种》，《自私的基因》，《机器人叛乱》——2月学的三本书，都有些难，也颠覆了我的一些观点，基因 与模因，到底什么主宰我们的行为？如何做一个理性的人？我们存在的价值？是为基因服务，还是为载体服务？

- 并没有完全读完所有的章节，每本书一章，其中《心灵种种》，虽然看了丹尼特的视频，还是不大明白。但却多了一个意识：自己是自己的主人，自己也是自己最好的朋友。时刻，我们需要考虑头脑里的“自发式”思想是否在误导我们？时刻，用理性的思维来审视自己的行为和判断？

   **通过学识的提升，理性的提升，可以让我们更好的决策和生活。**

- 生活中的一个例子：在犹豫是否做一件事时，听到这句“再不疯狂就老了”。第一反应，有理，惯性思维，准备去做那件“疯狂”的事。但后来反思，是不是疯狂的人，就不老呢？疯狂的人，也会老。老的人，也有不疯狂。用演绎逻辑里的证伪（4卡片问题，出处《机器人叛乱》），分析：如果P则Q，通过P和非Q可以证伪。那么结论是，疯狂和老不老没有直接关系，如是，我可以选择不去做这件“疯狂”的事。瞬间，冷静了。

- 另外一个例子，看完《剪刀手爱德华》第一反应，爱情好感人。用理性思维想：因为爱一个人，就可以去偷盗，去杀人吗？如是的爱是真爱吗？还是以真爱之名，在行“小我”呢？哪个是基因，哪个是模因？是否理性呢？最后冷静了，客观的看待这电影里的唯美和可商榷的地方。也许我们真的是机器人，而需要进行时刻警惕，叛乱，从而成为更好的自己。

- 从理性思维开始慢慢回归，生活决策不一样，越来越能自己做主了。生活，生命不止是繁衍，如同《自私的基因》里所说：

> 我们的基因可能是不朽的，但体现在我们每一个人身上的基因集体迟早要消亡。...我们不应该指望生殖能带来永恒性。但如果你能为世界文明做出贡献，如果你有一个精辟的见解或作了一个曲子，发明了一个火花塞，写了一首诗，所有这些都能完整无损地流传下去。即使你的基因在共有的基因库里全部分解后，这些东西仍能长久存在，永不湮灭。...苏格拉底、莱奥纳多、哥白尼、马可尼等人的觅母复合体在今天仍盛行于世，历久而弥坚。
But if you contribute to the world's culture, if you have a good idea,compose a tune, invent a sparking plug, write a poem, it may live on, intact , long after your genes have dissolved in the common pool. Socrates may or may not have a gene or two alive in the world today, as G.C.Williams has remarked, but who cares? The memecomplexes of Socrates, Leonardo, Copernicus and Marconi are still going strong.

- 从这个意义上，开始希望能够留下一些跨越长时间周期的东西，不妄来一世。也许，审美在变，如同阳老师的文章里所说：

> 生活大概就是这样，很多东西都在分分秒秒地消逝，然而，这露水的世上，有卿云烂兮，纠漫漫兮。

- 比如：”驿寄梅花，鱼传尺素“，比如” 陌上花开，可缓缓归矣，比如剪刀手爱德华里的圣诞夜雪花，比如如同一张A4蓝色纸的天空，比如春日里“种杏栽桃待花开”。

 -  似乎，2月，我因此而豁然开朗，清晰的知道，自己是最爱自己的那个人；通过阅读了解了那个优雅的自己。不再孤独。同时也学会了，更优雅，更柔软的欣赏这个美好的世界。


> 我们都是孤独的刺猬，只有频率相同的人才能看见彼此内心深处不为人知的优雅。

  **世界上我们自己就是那个能感受到自己的人，在诺大的世界里，我们因为学习，而更了解自己，因为对自己的这份珍贵的懂得而不孤单。**

**Comment by violettianjie** [comment]
# 201703

**Comment by violettianjie** [comment]
# 201704

**Comment by violettianjie** [comment]
## 201705  含笑饮毒酒乎？

5月读了三本社会心理学的书，对于了解别人如何试图说服自己的方法有了更理性的认识。如果说以前，是凭直觉判断对方是否在使手段或技巧，而现在则是凭理性思维判断对方是否在使何种手段或技巧？

张爱玲说 爱情是含笑饮毒酒，明知是毒酒而饮。

当我们能准确判断对方在使用销售技巧或心理技巧引导你的时候，心里明知被骗而甘愿一笑而饮，是执著还是傻瓜还是洒脱？难以评价。

学习了这三本书的知识，可以帮助判断是否毒酒，并不能帮助你确认是饮还是不饮，却可以让你不管是饮还是不饮，都含笑去做这一切。

难怪，阳老师要说学习了这些技巧，但要在善良的指导下适当运用，而不要过了。

技巧本身是剑，重剑无锋，还是利剑伤人，不是由剑决定，而是由剑客决定。

你可以在知道别人对你用剑的时候，大哭一场；仍然可以决定用何种方式去面对，选择爱与慈悲，还是选择嗔恨与报复，决定了我们会有怎样的人生，怎样的幸福感。

愿，面朝大海，春暖花开，你我含笑共饮一杯茶，敬天、敬地、敬海洋、敬自己。

**Comment by violettianjie** [comment]
# 201706  创造者之花——致一个月前的你

>如果只在不被辜负时去信任，只在有所回报时去爱，只在学有所用时去学习，那么就放弃了人之为人的特征。——《激情与自律》马奇

##  嫦娥有悔 碧海青天

你看到自己的人生脚本——小粉帽的“永不”脚本，如同看到一部你一生的故事的电影。认为自己不值得获得美好的人事物的信念，一次次在过往中重复。当电影的结尾曲响起，想对你说

>从今以后，许可你做自己，放下不关注自己而只想帮助别人的念头，放下想向父亲及所有类似父亲的角色证明自己的行为，关注自己，允许自己。你手上有很多钓鱼许可证，你可以自由选择去钓鱼，还是不钓鱼。

你知道了自己曾经是一个机器人，出厂设置为单线程单任务的机器人，如今这个机器人开始了版本升级，走出基因的限制，第一次写出了版本升级说明书，开始创造属于自己的模因，在大千世界留下美与创造的痕迹。


## 瀚海阑干 碣石潇湘

当你了解到人与人的三种关系：工具性关系、情感关系、混合性关系后，你明白了为什么你会和一些人有让你迷惑的相处关系。最初的工具性关系，在某一阶段变成了混合性关系，而你不停的试图把它变成情感关系。这种彼此定位的矛盾、不清晰，导致处理事情的纠结与悖论。你以为的无怨无悔，背后是有着人情往来的深刻内涵，不因为你不懂，它就不存在。面子、人情，是东方社会躲不开的差序格局的体现，如同大海里的碣石，你得用成人角色去面对，而不是儿童角色去逃避。

你开始明白
>在工作中防备却在友谊中放松，在感情中讨好却在家庭中索取

这种模式的不可取，这种分裂的处理方法为你的人生带来的是更多的烦恼，而非愉悦。
解决方案是整合生活的所有面，用一套价值观和行为方式来简化对待。如此，你用统一的逻辑去面对他人，降低人生复杂度，节省心力的消耗，开启赢家脚本，实现自己与世界的协议。

## 海阔鱼跃 天高鸟飞

通过阅读三本关于关系的书，你开始理解生活中充满悖论。人生的最小故事，不止有英雄之旅的白色，不止有黑暗之旅的黑色，还有含笑饮毒酒的灰色。而灰色，是更多的常态。如同诗歌反映了人生的复杂性，用诗歌去探索人生的悖论，去理解他人，去拓展自己的认知边界，提升自己的影响力和领导力，从而海阔天高，自由翱翔。

你开始理解了这种不确定性的美，不完美的美，充满悖论的美，将激情与自律统一，不再迷恋单纯的个人英雄主义，而是从历史中看到每个独立个体的付出的细微之美。人如产品，刷新了自己这个产品的灵魂：做一个发现美、基于内在动机的、不断成长的创造者。

说完“你好”之后，你开始行动，面朝大海，种下创造者之花。

**Comment by violettianjie** [comment]
## 201706  从网络联结反思职场经历

反思自己的四段职业生涯，如同春夏秋冬的一次轮回。

## 春满武林——强连接的阶段（2005-2012），杭州

毕业后在杭州一家it公司工作7年， 顺风顺水，没有太多起伏，点点收割。人际上局限在小圈子里的强连接。工作占用了大量时间，作为大公司的组块，没有与外界建立弱联结。

收获了一定职业化的成长，各种职业技能，缺乏外部体系弱联结网络的信息和扩展的能量。

## 夏游返乡——弱连接的阶段 （2012-2014）新西兰，成都

2012年初，去新西兰 working holiday 一半年（基本没有人际联结）。其后来到成都，和父母同在一个城市，通过弱联结认识的陌生朋友，合作做有机产品小生意。第一次扩展了弱联结，并应用到工作中。

回到成都的第一个月，把成都认识的所有人都梳理了一遍，重新建立连接。也成为我后来4年的人际支撑网络。

这次创业的尝试，维系仅2年。与合作方分开。原因之一在于 没有形成足够多的结构洞，广泛的弱联结，因为行业转换，没有得到新的强连接支撑。

## 秋隐天府—— 形成结构洞的阶段 （2014-2016）成都

休整阶段，除了简单的投资，将时间用于学习插花、烹饪，旅游、内观，翻译。这些零散的事，反而形成了若干结构洞。2年多时间，把曾经的同事、同学、朋友们组织起来，相互认识，成就了她们之间的合作。其中一个前同事，把我的其他各种关系的朋友联系起来（对她是弱联结，变成强连接），成立了一个有机生活馆，持续创业进行中。我把之前积累的有机行业所有相关资源，都介绍给了她。成人之美，也是幸福。

这个阶段，我在成都的各种人际关系，进行了一次以我为核心的重整，然后又分散形成各种网络，这个过程中体会到结构洞的魅力。

不足是，之前在杭州，北京等各地的连接资源，没有延续，或延续很少。对于我的人际网络中更大的资源，更多的分布在各大城市的同学、朋友、前同事、茶友等，没有进行很好的梳理、维护、管理。

这个时候，认识了开智，对于地域选择，有了新的认识。

## 冬居鹏程——缺乏社会网络化的阶段（2016-2017），深圳
 
通过之前曾经强连接，变成弱连接的深圳朋友，我又来到深圳，回到通信行业。

这一次，没有仔细梳理在深圳的所有已有关系，而是将所有精力放在这份工作，仅有的一点弱连接支撑上，导致基础不稳固。没有建立自己的社会资本支撑。

这一次，从低信息区域到更高信息区域，同事间的信任没有足够建立。在杭州积累的强连接的前同事网络，有重新的弱连接，成了我新工作的某一部分，但没有形成小世界网络和结构洞。缺乏足够的强连接、弱连接的支持。

幸运的是，同时遇到开智，对自己的思维进行了一次刷新。找到自己的内在动机，寻找自己人生的零度偏离。

在同时通识部落和认知写作学课程的压力下，我放弃了这份工作，选择了辞职。


回顾几次转折，是人生脚本的一次次重复，是问题的一次次轮回，这次，我选择直面它，点滴改进。重新开始思考自己的网络，重新开始造洞，去走自己的英雄之旅，突破人生的脚本。

**Comment by MindWare2016** [comment]
从今以后，许可你做自己，放下不关注自己而只想帮助别人的念头，放下想向父亲及所有类似父亲的角色证明自己的行为，关注自己，允许自己。你手上有很多钓鱼许可证，你可以自由选择去钓鱼，还是不钓鱼。
谢谢。

**Comment by violettianjie** [comment]
##复盘 报道帖20161211 的进展

名号 紫儿。// _（田捷，为统一，降低复杂度，改为真名）_

坐标 深圳

Blog http://blog.sina.com.cn/violetea

生命故事（你是谁，从哪里来，要到哪里去）
四川妹子，求学江城武汉7年，毕业后天堂之都杭州工作7年，新西兰Working holiday 半年，回到成都4载，学习了两年中华花艺插花。如果说7年是一辈子，在第5辈子开始的第0年，来到鹏城深圳工作。
本科专业是 计算机和法学；研究生研究方向是神经网络。
喜欢静以品茗、动以旅游。
在这个信息社会，这个全球化的时代，在哪里不重要，我们如果愿意，可以去到我们想要的任何一个地方。
而生命的时间是有限的，我希望我有限的生命，能够做到离开时“此心光明，无憾”。
短短的3万天，可以每天多学一些知识，减少一些贪嗔痴，通过积累和付出爱，在这个星球上留下来过生命的痕迹。

你最擅长的一项技能是什么？通过什么样的方法学会的？（告诉我们你的学习方法论）
如果内观禅修算一种技能的话，坚持了4年，每天早晚各一小时，每周尽量一次共修2-3小时，每年一次10日课程，这样积累，坚持。无他。
如果内观禅修不算技能，如果旅游算的一项技能的话，24岁前（研究生毕业前）利用节假日自助走完国内所有省自治区直辖市（以至少到过一个城市为准）。方法是PDCA，坚持按项目管理的方式来旅游，制定计划，分解任务，执行，回顾，再调整。

你最喜欢的网络科学、认知&神经&心理科学、计算机科学、数学与诗学……任意领域的一本书是什么？它对你有什么改变？
《正见》 增强了觉知和平等心。

未来你的输出计划是什么？（写下来，所有人都是你的见证人！）
按照部落计划完成高质量卡片输出。  //170621:每本书坚持写卡片，ok。
每精读完一本书，输出读书笔记。 //170621:输出2篇完整读书笔记，其余待补。
每季度结束，输出一篇 部落学习收获分享。//170621:输出3篇比较完整的收获分享。其余不够完整。需要把分享／读书笔记都当成作品。

你能为部落做哪些事？（欢迎脑洞大开~ ）
组织深圳线下活动。//170621 复盘：组织了一次，没有成功。

**Comment by violettianjie** [comment]
##.  复盘 认知写作班 170307 自我介绍

**名号**： 紫儿。// _田捷，为统一，降低复杂度，改为真名_
           爱好有点多，参考开智某同学分享的内容，特制作紫儿使用说明书，欢迎输入序号，和我交流。这样会不会比较方便？

- 01  如果想聊琴棋书画诗与花，请叫我紫儿。中华花艺基金会会员，学中华花艺第四年。
- 02  如果想聊柴米油盐酱醋茶，请叫我紫儿。心饮茶人。
- 03  如果想聊内观禅修 Vipassana Meditation，请叫我紫儿。坚持练习第6个年头。
- 04  如果想谈工作，请叫我 田捷。
- 05  其他，随意。
           
// _田捷，为统一，降低复杂度，改为真名_

**坐标**：深圳

茫茫网海，你可以在这里找到我：

 Blog： [紫儿](http://blog.sina.com.cn/violetea)      

 公众号：紫儿       （组织翻译的一本《有机家庭生活》书的连载）
 
 GitHub 号&微信号：  violettianjie

**个人介绍**：

写作 ，一个安定心灵的地方。

> 文养气，诗养心

希望可以用写作养心与气。 // _170621复盘：达到这样的初心，安放心灵。_

在四川度过童年，少年时光。在武汉读本科、研究生七年，杭州工作七年，新西兰晃悠大半年，成都四年，现在深圳。终身学习者，希望可以和小伙伴一起同分享，共成长。

- 写出三个在无外力情况下你做过的重要决定

1、初二决定转学
2、辞职去新西兰打工度假
3、离开成都，到深圳工作

// _170621:对这三个决定，有了新的认识。对于决策有了新的认识。对于允许有了新的认识。_

**Comment by violettianjie** [comment]
@MindWare2016   谢谢你的反馈，父亲离去你估计很难过吧，需要一段时间去调适，因为父亲是人生关键的人物。你 “釜底抽薪，背水一战”的勇气让我佩服。祝福你，相信什么时候都不晚，你可以实现你自己定义的人生脚本，再次起航。

**Comment by violettianjie** [comment]
## 201707 

本月主题：通识部落（7 月）：跨学科思维训练

第一周：[《查理·芒格的智慧:投资的格栅理论(原书第2版)》](https://github.com/OpenMindClub/OpenMindWorld/issues/308)
第二周：[《经验的疆界》](https://github.com/OpenMindClub/OpenMindWorld/issues/313)
第三周：[《莎士比亚、牛顿和贝多芬》](https://github.com/OpenMindClub/OpenMindWorld/issues/317)

本月：额外阅读了《马奇论管理》，本月总结致敬马奇老爷子。

## CEO与诗人

1983年哈佛大学教授迦纳提出了一个关于智力方面的“多元智能”架构，把智力分为 语文能力、逻辑-数学能力，空间能力，肢体-动觉能力，音乐-节奏能力，人际能力，内省能力，自然观察能力。

CEO们往往内省能力很强。写作好的人的职业可以是作家／诗人或CEO,因为CEO们明白工作中的不确定性，同时要向员工去传达确定性，往往对语文能力也要求很高。

世界的矛盾，要求管理者既保持对人生矛盾、悖论、模糊和正反情感的清晰认识（如智慧、美和学习），同时又信奉简单、明确、一致和确定的辞令（如管理规范和实务）。要想保持这种双重性，往往需要有请诗歌出场。

马奇讲领导力时提到诗人与管道工。好的CEO既像管道工一样勤奋、踏实，又有诗人通过诗歌表达不确定性和复杂性的能力和高度的意向性。


提升意向性了解他人或表达自我的两种不同思路：一是在真实的商业世界中，通过实践的行为，不断反省，去了解他人，去复盘行为决策的结果是否符合预期，并不断调整优化，达到企业的战略目标。一是在虚拟的文字世界中，通过故事或诗歌，去传递自己对世界，对他人的理解、看法、观点。

区别在于：前者可以通过业绩、数字等去看结果，风险也更大；后者需要更长的大时间周期去检验，风险小。

每个人都可以用诗歌探索矛盾和悖论，探索相互冲突的感情能否同时并存，探索活在多重世界、体验多重感情是一种什么感觉，探索丑在造美活动中存在什么作用。

如同马奇所说

> 大多数时候，诗歌透过两个镜头看世界，一个清晰的，一个模糊的。因为生活既清晰又模糊，人既可敬又卑鄙。两方面同时存在，你必须同时看到它们，不要妄图调和它们之间的冲突，而要把它们都看作人生的本质。


写作之用，在无用之美，安放心灵；写作之美，也在有用之善，与世界交互。

如同人的最小故事，有三类：光明的，黑暗的，灰色的。诗歌、管理或者说创业者的故事更多不是简单的黑与白，而是灰色的，如同爱情的含笑饮毒酒，更符合现实的生活。当我们有了更多的包容，更了解人性的两方面，不去妄图调和，接受这种冲突，就更理解人性，更理解他人，具备影响更多人的力量。

**Comment by violettianjie** [comment]
## 201708  本月主题：西蒙

[我生活的种种模式 ](https://github.com/OpenMindClub/OpenMindWorld/issues/332)

[人工科学 ](https://github.com/OpenMindClub/OpenMindWorld/issues/338)

[穿越歧路花园 ](https://github.com/OpenMindClub/OpenMindWorld/issues/344)

## 穿越歧路花园的迷宫

美国的赫伯特·西蒙（Herbert Simon，中文名：司马贺）和阿根廷的 博尔赫斯（Jorge Luis Borges ）两位文理不同领域的大师都不约而同的在自己的作品中用到迷宫（maze）隐喻生活。

1973年，西蒙在阿根廷和博尔赫斯有一次会面，就迷宫隐喻有趣对话。博尔赫斯有写《巴别塔的图书馆》，而西蒙有写《 苹果：迷宫的故事》【西蒙用这个故事来阐述1956年的论文《理性选择与环境结构》（Rational choice and the structure of the environment,1956/3/31, Psychological review）中描述的「迷宫模型」】。同样是把生活隐喻成迷宫，博尔赫斯的描述是在一个混乱的世界中进行有序探索，而西蒙是在有序、复杂世界中进行启发式探索。

西蒙的一生，横跨计算机科学、认知科学、管理学、经济学、政治科学等多个领域，得过诺贝尔经济学奖、计算机领域的图灵奖。他有9个博士头衔：1943年的芝加哥大学政治学博士学位、1963年凯斯工学院科学博士学位、1963年耶鲁大学科学博士学位、1963年法学博士学位、1968年瑞典伦德大学哲学博士学位、1970年麦吉尔大学法学博士、1973年鹿特丹伊拉斯莫斯大学经济学博士、1978年米之根大学法学博士、1979年匹兹堡大学法学博士。

这么一位跨界的大师，却自述他是个偏执狂，他一生都在研究“决策”。如何找到迷宫里的路？西蒙说

> 在我们到达迷宫的岔路时，“某种东西” 帮我们选择走哪条岔路。我研究的原因以及我对迷宫着迷的原因是我一直想观察人们在面临岔道时的行为并试图理解他们为什么向左走或向右走。

他提出了有限理性的概念。人类的理性是有限的。这些界限不是由激情或无意识决定的，而是由人类这个生物体作为信息处理者本身固有的局限性所决定的。简而言之，

> 人脑形成和解决复杂问题的能力相对于问题的大小而言是微不足道的，因为要
解决问题就需要面对现实世界的客观的理性行为。
用有限理性去面对生活中的不确定性。人生如同迷宫，决策的结果是否是最优，永远没有标准答案。

在西蒙的自传《我生活的种种模式》里有提到博尔赫斯的诗，来形容用把生活的种种复杂性当成一种游戏。

> 对于爱我已变得太老 ／我的爱／ 已使我年迈 ／但还不至于 ／老眼昏花／ 长夜茫茫／ 笼罩着我们。 ／那深藏在爱 ／和激情之中的什么／ 仍使我惊异。

这里，惊异的英文amazement，迷宫的英文maze，是一个有趣的文字游戏。

愿你我都能把生活的复杂性当成一场游戏，用有限理性的钥匙去穿越生活的歧路花园，走出迷宫。

**Comment by violettianjie** [comment]
# 南山是一座什么样的山？

## 南山有台，北山有莱

　南山生柔莎，北山长嫩藜。世界如此之大，你是选择南山，还是北山？南山和北山有什么区别？少男少女少年们，你的青春时代，面对无数的选择，在喧嚣的世界，你坚强的打拼，已经忘记了何为柔软。读到诗经里

> 南山有台，北山有莱。

   那一刻，你的心突然感到柔软。一种力量如同种子，破土而出。


## 乐只君子，德音是茂
   君子真快乐，美名必永驻。你问自己：为什么要在繁忙的工作之余选择这门认知写作课，看似无用的功课。写作？干嘛？心里一个声音如同洪波涌出，快乐，安放心灵。

> 我们都是孤独的刺猬，只有频率相同的人才能看见彼此内心深处不为人知的优雅。

  读到

> 天上有行云，人在行云里

  的快乐，让你决定，写作，因为快乐。上写作课，因为众行远，携手师友，乐只君子。

## 白云在天，道里悠远

  认知写作课的内容，很多突破了你的认知。你抓住了最小行动，坚持完成了每周的大作业，千字文。开始为完成作业，逐渐感到心被安放在一个宁静之处，浮躁、喧嚣被每周的千字文如扇子扫过。白云在天，这条路很长，一点点看着自己写作中暴露出来的特点，一点点通过写作清单，通过练习去改进，日有寸进。缓慢而悠长，前路漫漫......
  同时进行的大作业BP，也一天天在讨论中进行。
  忽然一日，结业路演之时。时间真快，道路还在远方，写作成为生命中的一部分。
  
  回顾这一次的课程，想到这句 ：南山是一座什么样的山？认知写作课是一门什么样的课？

  没有标准答案，诗歌里的悠然见南山，温暖了一代又一代的人们；一期又一期的认知写作课，如同悠然见南山里的南山。你准备好了吗？一起踏上悠远的写作之道，白云在天，写作在下，一路同行，欢迎你，新同学。

**Comment by violettianjie** [comment]
## 201709  月度主题 知识创造 

智识的生产技术 (豆瓣)
创造知识的企业 (豆瓣)
知识大融通 (豆瓣)


月度复盘 [知识的镜子 ](https://github.com/violettianjie/OpenMindWorld/blob/master/50w.md)

**Comment by violettianjie** [comment]
201710 月度主题  复习。

# 持剑上昆仑



**量级跃迁是什么？**

## 昆仑之巅



数量级是指数量的尺度或大小的级别，每个级别之间保持固定的比例。

量级是对系统当下规模作描述的一个直观属性，可以是思维的抽象层级，可撬动资源的数量级，看待行业的空间尺度，预测趋势的时间提前量。不同量级意味着不同规模的系统稳定构造，构成元素的集大小，一个空间描摹的标度概念，而这个系统元素集合里面，关键是结构法则的差异，是系统的使命指向，组织机体的基因或灵魂。

跃迁是质变，意味着从一种法则变换成更宽广的法则，是发展路径的更高定位，是基因的重组与进化，是结构化的更新。


量级跃迁是从量变到质变，提高效率、节省成本、更接近底层的创造。

**如何实现量级跃迁？**

## 纵横三万里

量级跃迁的最小路径：通过读书、写作等输出与世界交互，跨学科多维度同时应用多个高阶模型，矛盾的自洽以及相互印证，完成压力测试之后应用到生活中更多方面。在这个过程中机遇风险并存。我们得到大时间周期的复利同时要考虑边际效益递减的风险。用7%的社会网络的原理去应对风险，到了7%节点后，继续往上一级跃迁。


### 网络科学之剑

量级的提升会涉及到如何理解冥律？如何理解异步律？如何从网络科学的维度来看待万事万物？

> 网络科学大大地扩展了人的认知边界。人类思维习惯是线性因果思维，但是网络科学让你意识到幂律、多层、尺度、分形，自组织等观念。

> 网络科学训练的是复杂思维，从因果论到目的论，从概率到贝叶斯，从理论到模型，从亚里士多德逻辑到维特根斯坦的多值逻辑。—— 阳志平

### 认知科学之剑

基于时空隐喻，人类大脑对空间认知比对时间认知有更高优先级。《创新算法》提到系统构成的三要素：成本、空间、时间，即STC算子。用成本--空间---时间的维度，来思考量级跃迁，量级跃迁偏成本和空间。我们比较习惯从时间维度来思考问题，而量级跃迁的思维和行动会来带成本的节省，和空间的多样性，保持大时间周期的持续性。 成本>空间>时间的原则可以加速量级跃迁的过程。

批量处理、降维（区分原始数据和演绎数据、容易沟通（一群人>一个人）、可复用（多个场景>一个场景）、大时间周期等都是可以帮助我们实现量级跃迁的细节的具体化行为。

涉及的理论： [原型范畴论PrototypeTheory](https://en.wikipedia.org/wiki/Prototype_theory)。（认知语言学）。

### 数学的之剑

用符号代替语言，用数学符号来思考，可以规避我们单线条因果思维的缺点，实现空间变化，进行降维和旋转，得到微妙的结论。重点不是精确性，而是转换思考方式；重点不是真的通过数学思考获得正确答案，而是**用数学认知工具来代替语言，进行「问题表征」**，比如对称、旋转、降维、正弦、正态分布等。

> 数学对我经常是思维的语言。我不知道精确的含义是什么（阐明其含义是我今天的重要研究目标之一），但我能设法解释它。在解决一个问题时，我肯定不经常用词语来思考，而是用较抽象的表征，它也许是图画或图表，而部分是符号。数学——这种非词语思维——是我发现的语言。它是我用以产生新观念的工具。这种数学是相对不精确、不严谨，但有启发性的。必须核查用它得到的“解”的正确性。这是物理学家的数学或工程师的数学，而不是数学家的数学。
——《我生活的种种模式》，西蒙，1998，P143

> {A}——>[ A1, A2 , A3 …] ——> 【A】
{B}——>[ B1, B2 , B3 …] ——> 【B】
从 {A}--{B} 转变为 【A】--【B】对比。
从 A/B 的表面比较，到 A/B 的深层次比较。
—— @heshenxian1  issue [#298 ](https://github.com/OpenMindClub/OpenMindWorld/issues/298#issuecomment-325948637)

涉及数学理论：**[控制论Cybernetics](https://en.wikipedia.org/wiki/Cybernetics)**（1948年诞生，控制论之父：诺伯特·维纳（Norbert Wiener,1894~1964））、群论／逻辑类型理论。

###  认知写作学之剑

问题转化为如何从我心，变成理解他心，到理解天下心？如何把意向性从1-2的层级提升到5-7的层级？

借用波利亚《怎样解题》的思路。量级的提升 、复杂性思维的建立，某种意义上是用另一种方式书写自己的人生故事。用第二序的思维来改变

> 控制论中，因果解释或意义的解析一点也不重要……转化所关切的是发生了什么改变，而不是改变为什么发生
—— 《改变：问题形成和解决的原则》之章七 第二序改变

借用**故事——模型——行动**的方式。从多个学科的维度定义这个问题，抽象出相应的模型（根据人脑的认知可以限定在四个），细化为具体的最小行动以及用不同时空的“正反上下、古今中外”来进行应用。 

如果只是用模型解读，容易陷入理性的束缚；如果只是用故事来解释，容易难逃自己导演的脚本；如果只是用行动去实践，难免陷入唯我或唯他的功利实用。用宇宙／世界／社会层级来丰富自己的大脑，知晓世界之大，才能让 故事、模型、行动更加具有生命力。但如果只是停留在宇宙／世界层次，容易走向神秘主义。因此，需要我们在所有层级进行感受、解释、行动，知理、知事、知人、知天、知道。

## 光寒十九州

人一生中重要决策不会太多，人生中关键的量级跃迁也不多，**如何增大面对重要的量级跃迁时成功的概率？**——[压力测试Stress testing](https://en.wikipedia.org/wiki/Stress_testing) 。量级跃迁个人可以进行压力测试的方向： [学习习惯的建立](https://mp.weixin.qq.com/s/JQMC5Lgove67Zij4RiNn0Q)、[知识系统的管理](https://mp.weixin.qq.com/s/j6fqcvzER6gv1JnPBqnYkA)、写作。完成压力测试后，再应用到生活中其他方面  如：投资、收入、结婚、理财......

让你我诗酒趁年华，迈步从头越且把三年五载过成一生一世，持剑上昆仑。

- 参考书目：

《改变》
《怎样解题》
《创新算法》
《我生活的种种模式》
《社会网络分析：方法与实践》
《找工作》
《结构洞》

- 致谢：

感谢参与[讨论](https://github.com/OpenMindClub/OpenMindWorld/issues/349)的：linfeng365，wangyiping ， robin2017s，alissli，sherazhang
本文部分内容借鉴了 阳老师、十三维的观点。
